diary/__init__.py
from flask import Flask, request, url_for, redirect, session, flash

app = Flask(__name__)
app.config.from_object('diary.config') 
app.config.from_object('lib.config')

from lib.db import init_db
init_db(app)

from functools import wraps

# ログインチェックデコレータの定義
def login_check(view):
    @wraps(view)
    def inner(*args, **kwargs):
        if not session.get('auth_id'):
            flash('まだログインしていません', 'danger')
            return redirect(url_for('login'))
        return view(*args, **kwargs)
    return inner

from diary.views import auth, diaries

app.register_blueprint(diaries.diary, url_prefix='/diaries')

diary/views/auth.py
from flask import render_template, request, url_for, redirect, session, flash
from diary import app, login_check
from lib.db import db
from lib.models import User

# トップページを表示
@app.route('/')
@login_check
def top():
    user = User.query.get(session.get('auth_id'))
    return render_template('top.html', user=user)
    
# ログインページを表示
@app.route('/login')
def login():
    # ログイン済みかどうかをチェック
    if session.get('auth_id'):
        flash('すでにログインしています')
        return redirect(url_for('top'))
    
    # 未ログイン時のみ、ログインページを表示
    return render_template('login.html')

# ログイン処理
@app.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')

    user = User.query.filter(User.email == email).filter(User.password == password).first()
    if not user:
        flash('ログインできませんでした', 'danger')
        return redirect(url_for('login'))
    
    session['auth_id'] = user.id 

    flash('ログインしました', 'success')
    return redirect(url_for('top'))

#  ログアウト処理
@app.route('/logout', methods=['GET', 'POST'])
def logout():
    session.pop('auth_id', None)
    flash('ログアウトしました', 'success')
    return redirect(url_for('login'))

diary/views/diaries.py
from flask import render_template, request, url_for, redirect, session, flash, Blueprint
from sqlalchemy import or_
from diary import app, login_check
from lib.db import db
from lib.models import Diary
from datetime import datetime 

from functools import wraps

# ログインチェックデコレータの定義
def user_check(view):
    @wraps(view)
    def inner(*args, **kwargs):
        diary = Diary.query.get(kwargs.get('id'))
        if not diary or diary.user_id != session.get('auth_id'):
            flash('不正なアクセスです', 'danger')
            return redirect(url_for('diary.index'))
        return view(*args, **kwargs)
    return inner

diary = Blueprint('diary', __name__)

# 日記一覧画面
@diary.route('/')
@login_check
def index():
    # リクエストパラメータ
    keyword = request.args.get('keyword')
    page = request.args.get('page', default=1, type=int)

    # 日記クエリ（投稿日時降順）
    query = Diary.query.order_by(Diary.created_at.desc())

    # 自分の日記のみ取得
    query = query.filter(Diary.user_id == session.get('auth_id'))

    # キーワード検索
    if keyword:
        word = f'%{keyword}%'
        query = query.filter(or_(Diary.title.like(word), Diary.content.like(word)))

    # ページネーション付きで取得
    diaries = query.paginate(page=page, per_page=10)

    return render_template('diaries/index.html', diaries=diaries)
    
# 日記詳細画面
@diary.route('/<int:id>')
@login_check 
@user_check
def show(id):
    diary = Diary.query.get(id)
    return render_template('diaries/show.html', diary=diary)

# 日記投稿画面
@diary.route('/new')
@login_check 
def new():
    diary = Diary()
    return render_template('diaries/new.html', diary=diary)

# 日記登録処理
@diary.route('/create', methods=['POST'])
@login_check
def create():
    # リクエストパラメータ
    title = request.form.get('title') or ''
    content = request.form.get('content') or ''

    # バリデーションメッセージの処理（本当はモデルでやりたいが便宜上ここで）
    errors = []

    # タイトルは必須（空文字が入ってしまわないように）
    if not title:
        errors.append('タイトルを入力してください')
    
    # 本文は必須（空文字が入ってしまわないように）
    if not content:
        errors.append('本文を入力してください')
    
    # エラーがあったらフラッシュメッセージ＆リダイレクト
    if errors:
        for e in errors:
            flash(e, 'danger')
        return redirect(url_for('diary.new'))
    
    diary = Diary(
        user_id = session.get('auth_id'),
        title = title, 
        content = content, 
        created_at = datetime.now()
    )
    
    try:
        db.session.add(diary)
        db.session.commit()
    except Exception as e:
        print(e)
        flash('投稿できませんでした', 'danger')
        return redirect(url_for('diary.new'))
    
    flash('投稿しました', 'success')
    return redirect(url_for('diary.show', id=diary.id))

# 日記編集画面
@diary.route('/<int:id>/edit')
@login_check 
@user_check
def edit(id):
    diary = Diary.query.get(id)
    return render_template('diaries/edit.html', diary=diary)

# 日記更新処理
@diary.route('/<int:id>/update', methods=['POST'])
@login_check 
@user_check
def update(id):
    diary = Diary.query.get(id)

    # リクエストパラメータ
    title = request.form.get('title') or ''
    content = request.form.get('content') or ''

    errors = []
    
    if not title:
        errors.append('タイトルを入力してください')
    
    if not content: 
        errors.append('本文を入力してください')
    
    if errors:
        for e in errors:
            flash(e, 'danger')
        return redirect(url_for('diary.edit', id=id))

    diary.title = title 
    diary.content = content

    try:
        db.session.commit()
    except Exception as e:
        print(e)
        flash('更新できませんでした', 'danger')
        return redirect(url_for('diary.edit', id=id))
    
    flash('日記を更新しました', 'success')
    return redirect(url_for('diary.show', id=id))

# 日記削除処理
@diary.route('/<int:id>/delete', methods=['POST'])
@login_check 
@user_check
def delete(id):
    diary = Diary.query.get(id)
    
    db.session.delete(diary)
    db.session.commit()

    flash('削除しました', 'success')
    return redirect(url_for('diary.index'))

diary/templates/diaries/_form.html
<div class="mb-2">
    <label for="title" class="form-label">タイトル</label>
    <input type="text" name="title" id="title" class="form-control" value="{{ diary.title or '' }}">
</div>
<div class="mb-2">
    <label for="content" class="form-label">本文</label>
    <textarea name="content" id="content" class="form-control" rows="6">{{ diary.content or ''}}</textarea>
</div>

diary/templates/diaries/edit.html
{% extends 'layout.html' %}
{% block body %}
<h3>日記投稿</h3>
<form action="{{ url_for('diary.update', id=diary.id) }}" method="post">
    {% include 'diaries/_form.html' %}
    <button class="btn btn-primary">更新する</button>
    <a href="{{ url_for('diary.show', id=diary.id) }}" class="btn btn-light">キャンセル</a>
</form>
{% endblock %}

diary/templates/diaries/index.html
{% extends 'layout.html' %}
{% block body %}
<div class="row">
    <div class="col-3">
        <form action="{{ url_for('diary.index') }}" method="get" class="card">
            <div class="card-header">日記検索</div>
            <div class="card-body">
                <label for="search-keyword" class="form-label">キーワード</label>
                <input type="search" name="keyword" id="search-keyword" class="form-control" value="{{ request.args.get('keyword') or '' }}" placeholder="タイトル・本文">
            </div>
            <div class="card-footer">
                <button class="btn btn-success w-100">検索</button>
            </div>
        </form>
    </div>
    <div class="col-9">
        <div class="page-heading">
            <h3>日記一覧</h3>
            <div>
                <a href="{{ url_for('diary.new') }}">日記投稿</a>
            </div>
        </div>
        <div>
            {% for diary in diaries %}
            <div class="mb-3 pb-3 border-bottom">
                <div class="diary-title"><a href="{{ url_for('diary.show', id=diary.id) }}">{{ diary.title }}</a></div>
                <div class="diary-meta">
                    <div class="diary-user">{{ diary.user.name }}</div>
                    <div class="diary-datetime">{{ diary.created_at.strftime('%Y年%m月%d日 %H:%M') }}</div>
                </div>
            </div>
            {% endfor %}
        </div>
        <ul class="pagination">
            {% set page = request.args.get('page') | int or 1 %}
            {% set keyword = request.args.get('keyword') %}
            {% for p in diaries.iter_pages() %}
              <li class="page-item{% if page == p %} active{% endif %}">
                <a class="page-link" href="{{ url_for('diary.index', page=p, keyword=keyword) }} ">{{ p }}</a>
              </li>
            {% endfor %}
          </ul>
    </div>
</div>
{% endblock %}

diary/templates/diaries/new.html
{% extends 'layout.html' %}
{% block body %}
<h3>日記投稿</h3>
<form action="{{ url_for('diary.create') }}" method="post">
    {% include 'diaries/_form.html' %}
    <button class="btn btn-primary">投稿する</button>
    <a href="{{ url_for('diary.index') }}" class="btn btn-light">キャンセル</a>
</form>
{% endblock %}

diary/templates/diaries/show.html
{% extends 'layout.html' %}
{% block body %}
<h3>日記詳細</h3>
<div class="mt-4 mb-3 pb-3 border-bottom">
    <h1 class="h4">{{ diary.title }}</h1>
    <div class="d-flex justify-content-between">
        <div class="diary-datetime">
            {{ diary.created_at.strftime('%Y年%m月%d日 %H:%M') }}
        </div>
        <div class="d-flex">
            <a href="{{ url_for('diary.edit', id=diary.id) }}" class="btn btn-sm btn-outline-primary me-4">編集</a>
            <form onsubmit="return confirm('本当に削除しますか？')" action="{{ url_for('diary.delete', id=diary.id) }}" method="post">
                <button class="btn btn-sm btn-secondary">削除</button>
            </form>
        </div>
    </div>
</div>
<div class="pre-line">{{ diary.content }}</div>
{% endblock %}

diary/templates/layout.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Diary</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark">
            <div class="container-fluid">
                <a href="{{ url_for('top') }}" class="navbar-brand">Flask Diary</a>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{{ url_for('diary.index') }}" class="nav-link">日記検索</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container-fluid p-3">
        {% for category, message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}

        {% block body %}{% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

diary/templates/login.html
{% extends 'layout.html' %}
{% block body %}
<h3>ログイン</h3>
<form action="{{ url_for('login') }}" method="post">
    <div class="card w-50">
        <div class="card-header">ログイン</div>
        <div class="card-body">
            <label for="email" class="form-label">メールアドレス</label>
            <input type="text" name="email" class="form-control" id="email" value="">
            <label for="password" class="form-label mt-2">パスワード</label>
            <input type="password" name="password" class="form-control" id="password" value="">        
        </div>
        <div class="card-footer">
            <button class="btn btn-success">ログイン</button>
        </div>
    </div>
</form>
{% endblock %}

diary/templates/top.html
{% extends 'layout.html' %}
{% block body %}
<h3>トップページ</h3>
<p>{{ user.name }}さん、ようこそ！</p>
<form action="{{ url_for('logout') }}" method="post">
    <button class="btn btn-secondary">ログアウト</button>
</form>
{% endblock %}